export const businessTypes = [
  "Restaurante",
  "Hotel",
  "Café",
  "Barbería",
  "Salón de belleza",
  "Servicios automotrices",
  "Venta de autos",
  "Agencia inmobiliaria",
  "Gimnasio",
  "Farmacia",
  "Clínica dental",
  "Hospital",
  "Laboratorio",
  "Despacho de abogados",
  "Consultora",
  "Firma de contabilidad",
  "Firma de auditoría",
  "Supermercado",
  "Tienda",
  "Boutique de moda",
  "Ferretería",
  "Constructora",
  "Reparación de electrónicos",
  "Salón de eventos",
  "Planeación de eventos",
  "Estudio de Fotografía",
  "Agencia de viajes",
  "Veterinaria",
  "Imprenta",
  "Coworking",
  "Otro",
];

export interface BusinessActivity {
  businessName: string;
  revenueStreams: string[];
  channels: string[];
  valuePropositions: string[];
  commonNeedings: string[];
}

export const businessActivitiesMap: BusinessActivity[] = [
  {
    businessName: "Restaurante",
    revenueStreams: ["venta de platillos de comida", "venta de bebidas"],
    channels: [
      "reservaciones",
      "servicio para llevar",
      "consumo en el establecimiento",
    ],
    valuePropositions: [
      "renta de sala de juntas",
      "tarifas de servicio a domicilio",
      "servicio para eventos especiales",
      "spots para fotos",
      "restaurante temático",
    ],
    commonNeedings: [
      "Reservaciones en línea",
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Hotel",
    revenueStreams: [
      "tarifas de reserva de habitaciones",
      "uso de amenidades",
      "renta de espacios para eventos",
    ],
    channels: [
      "reservaciones",
      "plataformas de reserva en línea",
      "mostrador de recepción",
    ],
    valuePropositions: [
      "hospitalidad de alta gama",
      "vistas panorámicas",
      "spots para fotos",
      "paquetes todo incluido",
    ],
    commonNeedings: [
      "Reservaciones en línea",
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Cafetería",
    revenueStreams: [
      "venta de platillos de comida",
      "venta de bebidas",
      "venta de repostería",
      "venta de café en grano",
    ],
    channels: [
      "servicio para llevar",
      "consumo en el establecimiento",
      "preordenes en línea",
    ],
    valuePropositions: [
      "ambiente acogedor",
      "spots para fotos",
      "espacio ideal para trabajo remoto",
    ],
    commonNeedings: [
      "Reservaciones en línea",
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Barbería",
    revenueStreams: [
      "cortes de cabello y peinado",
      "productos de cuidado personal",
    ],
    channels: ["agenda de citas", "atención sin cita previa"],
    valuePropositions: [
      "cuidado personal personalizado",
      "experiencia de cliente premium",
      "spots estéticos",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Salón de belleza",
    revenueStreams: [
      "servicios cosméticos",
      "estilismo de cabello",
      "venta de productos de belleza",
    ],
    channels: ["agenda de citas"],
    valuePropositions: [
      "transformación de imagen integral",
      "spots para fotos",
      "asesoría experta en belleza",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Gimnasio",
    revenueStreams: [
      "cuotas de membresía",
      "sesiones de entrenamiento personal",
      "venta de suplementos",
    ],
    channels: ["registro en recepción"],
    valuePropositions: [
      "acondicionamiento de salud y bienestar",
      "equipo de fitness de primer nivel",
      "seguimiento comunitario",
      "clases de baile",
      "clases de yoga",
      "clases de box",
      "clases de pilates",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Farmacia",
    revenueStreams: [
      "venta de medicamentos con receta",
      "venta de productos de venta libre",
      "consulta médica",
    ],
    channels: ["recogida en tienda", "redes de entrega a domicilio"],
    valuePropositions: [
      "acceso inmediato a productos de salud",
      "disponibilidad de suministros esenciales",
      "asesoría de confianza",
      "servicio 24 hrs",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Venta en línea",
      "e-commerce",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Clínica dental",
    revenueStreams: ["procedimientos dentales", "tratamientos de ortodoncia"],
    channels: ["agenda de citas", "líneas de emergencia"],
    valuePropositions: [
      "atención médica especializada",
      "tratamientos sin dolor",
      "salud bucal a largo plazo",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Seguimiento post-servicio",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Hospital",
    revenueStreams: [
      "procedimientos médicos",
      "tarifas de hospitalización",
      "servicios de urgencias",
      "remisiones de especialistas",
    ],
    channels: [
      "triaje de emergencias",
      "programación de consultas externas",
      "mostrador de admisión",
    ],
    valuePropositions: [
      "atención médica crítica 24/7",
      "tecnología médica avanzada",
      "personal médico experto",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Seguimiento post-servicio",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Laboratorio",
    revenueStreams: [
      "tarifas de pruebas de diagnóstico",
      "kits de detección médica",
    ],
    channels: [
      "llamada telefónica",
      "clínicas de toma de muestras",
      "WhatsApp",
      "redes sociales",
    ],
    valuePropositions: [
      "diagnósticos de salud de alta precisión",
      "tiempos de entrega rápidos",
      "pruebas confidenciales",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Veterinaria",
    revenueStreams: [
      "tratamientos médicos para mascotas",
      "vacunación",
      "venta de alimento para mascotas",
    ],
    channels: ["agenda de citas", "atención médica de urgencia animal"],
    valuePropositions: [
      "atención médica compasiva para animales",
      "medicina veterinaria experta",
      "tranquilidad para los dueños",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Seguimiento post-servicio",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Despacho de abogados",
    revenueStreams: ["igualas legales", "tarifas de consultoría por hora"],
    channels: [
      "consultas legales profesionales",
      "portales seguros para clientes",
    ],
    valuePropositions: [
      "protección legal experta",
      "representación estratégica",
      "asesoría corporativa confidencial",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Recordatorios automáticos por WhatsApp y correo electrónico",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Firma de contabilidad",
    revenueStreams: [
      "honorarios por preparación de impuestos",
      "igualas mensuales de contabilidad",
    ],
    channels: [
      "integraciones con software contable",
      "revisiones fiscales anuales",
    ],
    valuePropositions: [
      "cumplimiento financiero estricto",
      "optimización de la carga fiscal",
      "reportes financieros claros",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Firma de auditoría",
    revenueStreams: [
      "paquetes de auditoría de cumplimiento",
      "informes de evaluación de riesgos",
    ],
    channels: [
      "evaluaciones corporativas presenciales",
      "portales de documentación seguros",
    ],
    valuePropositions: [
      "validación financiera independiente",
      "transparencia corporativa",
      "mitigación y reducción de riesgos de fraude",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Agencia inmobiliaria",
    revenueStreams: [
      "comisiones por venta de propiedades",
      "tarifas de gestión de rentas",
    ],
    channels: [
      "plataformas de listado de propiedades",
      "recorridos exclusivos de puertas abiertas",
    ],
    valuePropositions: [
      "catálogo de propiedades verificadas",
      "gestión fluida del cierre legal",
      "búsqueda de bienes raíces de alto rendimiento",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Coworking",
    revenueStreams: [
      "membresías de escritorios compartidos",
      "renta de escritorios dedicados",
      "renta de salas de juntas",
    ],
    channels: [
      "aplicaciones de reserva de espacios",
      "administración de la comunidad en el lugar",
    ],
    valuePropositions: [
      "espacio de trabajo compartido de alta gama",
      "ecosistema de infraestructura de networking",
      "conectividad de alta velocidad y operaciones confiables",
    ],
    commonNeedings: [
      "Reservaciones en línea",
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Supermercado",
    revenueStreams: [
      "venta de abarrotes al por menor",
      "artículos de distribución al por mayor",
    ],
    channels: [
      "cajas de cobro en tienda",
      "recogida en coche o entrega programada",
    ],
    valuePropositions: [
      "compras del hogar en un solo lugar",
      "disponibilidad de precios por volumen",
      "suministro de productos frescos esenciales",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Venta en línea",
      "e-commerce",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Tienda",
    revenueStreams: ["venta al por menor"],
    channels: ["mostradores de punto de venta"],
    valuePropositions: [
      "acceso local conveniente",
      "selección de inventario seleccionada",
      "experiencias de pago rápidas",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Venta en línea",
      "e-commerce",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Boutique de moda",
    revenueStreams: [
      "venta de ropa al por menor",
      "combinación de accesorios personalizados",
    ],
    channels: ["vitrinas estéticas en tienda", "perfiles de tienda en línea"],
    valuePropositions: [
      "estilo personal único",
      "spots para fotos",
      "curaduría estética de moda premium",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Venta en línea",
      "e-commerce",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Ferretería",
    revenueStreams: [
      "venta de herramientas y suministros",
      "tarifas de renta de equipo",
    ],
    channels: [
      "mostradores de atención técnica",
      "portales comerciales para contratistas",
    ],
    valuePropositions: [
      "suministro de equipo industrial pesado",
      "herramientas inmediatas para proyectos DIY",
      "asesoría experta en materiales técnicos",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Venta en línea",
      "e-commerce",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Imprenta",
    revenueStreams: [
      "producción de impresión por volumen",
      "procesamiento de diseño gráfico",
    ],
    channels: ["envío digital de archivos", "recogida física de muestras"],
    valuePropositions: [
      "materiales de marketing de alta resolución",
      "publicación confiable para empresas",
      "branding personalizado de mercancía",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Venta en línea",
      "e-commerce",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Cotizaciones automáticas",
      "Inventario automático",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Servicios automotrices",
    revenueStreams: [
      "tarifas fijas de reparación de autos",
      "venta de refacciones automotrices",
    ],
    channels: [
      "recepción en bahías de servicio",
      "reserva de diagnóstico digital",
    ],
    valuePropositions: [
      "operación segura de vehículos de carretera",
      "extensiones de garantía mecánica confiable",
      "diagnósticos vehiculares rápidos",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Cotizaciones automáticas",
      "Seguimiento post-servicio",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Constructora",
    revenueStreams: [
      "contratos de desarrollo estructural",
      "cotización de diseños de planos civiles",
    ],
    channels: [
      "licitaciones de proyectos corporativos",
      "revisiones de consultoría en sitio",
    ],
    valuePropositions: [
      "infraestructura de ingeniería arquitectónica escalable",
      "implementación estricta de códigos de seguridad",
      "gestión integral de finalización de obras",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Cotizaciones automáticas",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Reparación de electrónicos",
    revenueStreams: [
      "reparación de componentes de hardware",
      "tarifas de diagnóstico y pruebas",
    ],
    channels: [
      "mostradores técnicos de atención",
      "opciones de envío por correo para reparación",
    ],
    valuePropositions: [
      "extensión de la vida útil de dispositivos",
      "recuperación segura de datos críticos",
      "ahorro en recuperación de componentes electrónicos",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Cotizaciones automáticas",
      "Seguimiento post-servicio",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Venta de autos",
    revenueStreams: [
      "transacciones de activos vehiculares",
      "intereses por financiamiento automotriz",
    ],
    channels: [
      "pisos de exhibición en concesionarios",
      "catálogos web interactivos",
    ],
    valuePropositions: [
      "movilidad terrestre certificada y segura",
      "modelos de financiamiento flexibles",
      "acceso a transporte personal confiable",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Venta en línea",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Cotizaciones automáticas",
      "Seguimiento post-servicio",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Agencia de viajes",
    revenueStreams: [
      "comisiones de paquetes vacacionales personalizados",
      "corretaje de seguros de protección de viaje",
    ],
    channels: [
      "diseñadores de itinerarios personalizados",
      "canales de consultoría digital y telefónica",
    ],
    valuePropositions: [
      "coordinación sin preocupaciones de viajes internacionales",
      "descuentos exclusivos en rutas",
      "planeación logística de recreación curada",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Cotizaciones automáticas",
      "Seguimiento post-servicio",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Salón de eventos",
    revenueStreams: [
      "tarifas fijas de renta del lugar",
      "paquetes integrados de catering por niveles",
    ],
    channels: [
      "visitas físicas guiadas al lugar",
      "agendas de fechas de reservación",
    ],
    valuePropositions: [
      "configuraciones estructurales de gran espacio",
      "spots para fotos",
      "capacidad de servicio completo para eventos especiales",
    ],
    commonNeedings: [
      "Reservaciones en línea",
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Cotizaciones automáticas",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Planeación de eventos",
    revenueStreams: [
      "anticipos por diseño estructural de eventos",
      "margen por coordinación de proveedores",
    ],
    channels: [
      "portafolios de planeación estratégica",
      "canales interactivos de revisión digital",
    ],
    valuePropositions: [
      "coordinación y ejecución de experiencias sin preocupaciones",
      "acceso a redes de proveedores verificados",
      "producción conceptual creativa de entretenimiento",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Cotizaciones automáticas",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
  {
    businessName: "Estudio de Fotografía",
    revenueStreams: [
      "tarifas de sesiones fotográficas profesionales",
      "venta de impresiones y activos digitales",
    ],
    channels: [
      "calendarios de reserva de estudios",
      "portales seguros de distribución de galerías de medios",
    ],
    valuePropositions: [
      "captura y preservación de medios visuales cinematográficos",
      "edición estética de spots para fotos",
      "diseño de activos promocionales corporativos de alta gama",
    ],
    commonNeedings: [
      "Página web",
      "Manejo de redes sociales",
      "Notificaciones",
      "Gestión de clientes",
      "Optimización en buscadores (Google, Firefox y Edge)",
      "Panel de administración",
      "Conexión con WhatsApp",
      "Citas en línea",
      "Facturación electrónica",
      "Monitoreo de métricas de negocio",
    ],
  },
];

export const allServices = [
  {
    name: "Reservaciones en línea",
    types: [
      "Restaurante",
      "Hotel",
      "Café",
      "Salón de eventos",
      "Coworking",
      "Otro",
    ],
  },
  { name: "Página web", types: businessTypes },
  { name: "Manejo de redes sociales", types: businessTypes },
  {
    name: "Venta en línea",
    types: [
      "Supermercado",
      "Tienda",
      "Boutique de moda",
      "Ferretería",
      "Farmacia",
      "Venta de autos",
      "Imprenta",
      "Otro",
    ],
  },
  {
    name: "e-commerce",
    types: [
      "Supermercado",
      "Tienda",
      "Boutique de moda",
      "Ferretería",
      "Farmacia",
      "Imprenta",
      "Otro",
    ],
  },
  { name: "Notificaciones", types: businessTypes },
  {
    name: "Gestión de clientes",
    types: [
      "Barbería",
      "Salón de belleza",
      "Servicios automotrices",
      "Venta de autos",
      "Agencia inmobiliaria",
      "Gimnasio",
      "Clínica dental",
      "Hospital",
      "Laboratorio",
      "Despacho de abogados",
      "Consultora",
      "Firma de contabilidad",
      "Firma de auditoría",
      "Constructora",
      "Planeación de eventos",
      "Estudio de Fotografía",
      "Agencia de viajes",
      "Veterinaria",
      "Coworking",
      "Otro",
    ],
  },
  {
    name: "Optimización en buscadores (Google, Firefox y Edge)",
    types: businessTypes,
  },
  { name: "Panel de administración", types: businessTypes },
  { name: "Conexión con WhatsApp", types: businessTypes },
  {
    name: "Citas en línea",
    types: [
      "Barbería",
      "Salón de belleza",
      "Clínica dental",
      "Hospital",
      "Laboratorio",
      "Despacho de abogados",
      "Consultora",
      "Servicios automotrices",
      "Estudio de Fotografía",
      "Veterinaria",
      "Agencia inmobiliaria",
      "Otro",
    ],
  },
  {
    name: "Recordatorios automáticos por WhatsApp y correo electrónico",
    types: [
      "Barbería",
      "Salón de belleza",
      "Clínica dental",
      "Hospital",
      "Laboratorio",
      "Despacho de abogados",
      "Consultora",
      "Gimnasio",
      "Veterinaria",
      "Otro",
    ],
  },
  {
    name: "Cotizaciones automáticas",
    types: [
      "Servicios automotrices",
      "Venta de autos",
      "Constructora",
      "Reparación de electrónicos",
      "Salón de eventos",
      "Planeación de eventos",
      "Imprenta",
      "Agencia de viajes",
      "Otro",
    ],
  },
  {
    name: "Seguimiento post-servicio",
    types: [
      "Servicios automotrices",
      "Clínica dental",
      "Hospital",
      "Veterinaria",
      "Reparación de electrónicos",
      "Venta de autos",
      "Agencia de viajes",
      "Otro",
    ],
  },
  {
    name: "Inventario automático",
    types: [
      "Supermercado",
      "Tienda",
      "Boutique de moda",
      "Ferretería",
      "Farmacia",
      "Restaurante",
      "Café",
      "Imprenta",
      "Otro",
    ],
  },
  { name: "Facturación electrónica", types: businessTypes },
  { name: "Monitoreo de métricas de negocio", types: businessTypes },
];
