export const businessTypes = [
  "Restaurante",
  "Hotel",
  "Café",
  "Barbería",
  "Salón de belleza",
  "Servicios automotrices",
  "Venta de autos",
  "Agencia inmobiliaria",
  "Gimnasio",
  "Farmacia",
  "Clínica dental",
  "Hospital",
  "Laboratorio",
  "Despacho de abogados",
  "Consultora",
  "Firma de contabilidad",
  "Firma de auditoría",
  "Supermercado",
  "Tienda",
  "Boutique de moda",
  "Ferretería",
  "Constructora",
  "Reparación de electrónicos",
  "Salón de eventos",
  "Planeación de eventos",
  "Estudio de Fotografía",
  "Agencia de viajes",
  "Veterinaria",
  "Imprenta",
  "Coworking",
  "Otro",
];

export const industries = [
  { id: "alimentos", name: "Alimentos y hospitalidad", icon: "🍽️" },
  { id: "belleza", name: "Belleza y bienestar", icon: "💇" },
  { id: "salud", name: "Salud", icon: "🏥" },
  { id: "profesional", name: "Servicios profesionales", icon: "💼" },
  { id: "comercio", name: "Comercio y retail", icon: "🛍️" },
  { id: "industrial", name: "Industrial y construcción", icon: "🏗️" },
  { id: "eventos", name: "Eventos y creativos", icon: "🎉" },
  { id: "movilidad", name: "Movilidad y viajes", icon: "🚗" },
  { id: "mas", name: "Otros", icon: "✨" },
];

export const businessIndustryMap: Record<string, string> = {
  Restaurante: "alimentos",
  Hotel: "alimentos",
  Café: "alimentos",
  Barbería: "belleza",
  "Salón de belleza": "belleza",
  Gimnasio: "belleza",
  Farmacia: "salud",
  "Clínica dental": "salud",
  Hospital: "salud",
  Laboratorio: "salud",
  Veterinaria: "salud",
  "Despacho de abogados": "profesional",
  Consultora: "profesional",
  "Firma de contabilidad": "profesional",
  "Firma de auditoría": "profesional",
  "Agencia inmobiliaria": "profesional",
  Coworking: "profesional",
  Supermercado: "comercio",
  Tienda: "comercio",
  "Boutique de moda": "comercio",
  Ferretería: "comercio",
  Imprenta: "comercio",
  "Servicios automotrices": "industrial",
  Constructora: "industrial",
  "Reparación de electrónicos": "industrial",
  "Venta de autos": "movilidad",
  "Agencia de viajes": "movilidad",
  "Salón de eventos": "eventos",
  "Planeación de eventos": "eventos",
  "Estudio de Fotografía": "eventos",
  Otro: "mas",
};

export const allServices = [
  {
    name: "Reservaciones en línea",
    types: ["Restaurante", "Hotel", "Café", "Salón de eventos", "Coworking", "Otro"],
  },
  { name: "Página web", types: businessTypes },
  { name: "Manejo de redes sociales", types: businessTypes },
  {
    name: "Venta en línea",
    types: [
      "Supermercado",
      "Tienda",
      "Boutique de moda",
      "Ferretería",
      "Farmacia",
      "Venta de autos",
      "Imprenta",
      "Otro",
    ],
  },
  {
    name: "e-commerce",
    types: [
      "Supermercado",
      "Tienda",
      "Boutique de moda",
      "Ferretería",
      "Farmacia",
      "Imprenta",
      "Otro",
    ],
  },
  { name: "Notificaciones", types: businessTypes },
  {
    name: "Gestión de clientes",
    types: [
      "Barbería",
      "Salón de belleza",
      "Servicios automotrices",
      "Venta de autos",
      "Agencia inmobiliaria",
      "Gimnasio",
      "Clínica dental",
      "Hospital",
      "Laboratorio",
      "Despacho de abogados",
      "Consultora",
      "Firma de contabilidad",
      "Firma de auditoría",
      "Constructora",
      "Planeación de eventos",
      "Estudio de Fotografía",
      "Agencia de viajes",
      "Veterinaria",
      "Coworking",
      "Otro",
    ],
  },
  {
    name: "Optimización en buscadores (Google, Firefox y Edge)",
    types: businessTypes,
  },
  { name: "Panel de administración", types: businessTypes },
  { name: "Conexión con WhatsApp", types: businessTypes },
  {
    name: "Citas en línea",
    types: [
      "Barbería",
      "Salón de belleza",
      "Clínica dental",
      "Hospital",
      "Laboratorio",
      "Despacho de abogados",
      "Consultora",
      "Servicios automotrices",
      "Estudio de Fotografía",
      "Veterinaria",
      "Agencia inmobiliaria",
      "Otro",
    ],
  },
  {
    name: "Recordatorios automáticos por WhatsApp y correo electrónico",
    types: [
      "Barbería",
      "Salón de belleza",
      "Clínica dental",
      "Hospital",
      "Laboratorio",
      "Despacho de abogados",
      "Consultora",
      "Gimnasio",
      "Veterinaria",
      "Otro",
    ],
  },
  {
    name: "Cotizaciones automáticas",
    types: [
      "Servicios automotrices",
      "Venta de autos",
      "Constructora",
      "Reparación de electrónicos",
      "Salón de eventos",
      "Planeación de eventos",
      "Imprenta",
      "Agencia de viajes",
      "Otro",
    ],
  },
  {
    name: "Seguimiento post-servicio",
    types: [
      "Servicios automotrices",
      "Clínica dental",
      "Hospital",
      "Veterinaria",
      "Reparación de electrónicos",
      "Venta de autos",
      "Agencia de viajes",
      "Otro",
    ],
  },
  {
    name: "Inventario automático",
    types: [
      "Supermercado",
      "Tienda",
      "Boutique de moda",
      "Ferretería",
      "Farmacia",
      "Restaurante",
      "Café",
      "Imprenta",
      "Otro",
    ],
  },
  { name: "Facturación electrónica", types: businessTypes },
  { name: "Monitoreo de métricas de negocio", types: businessTypes },
];

// Maps each Gemini chatbot category (= industry id) to its services.
const categoryIndustryMap: Record<string, string[]> = {
  alimentos: ["alimentos"],
  belleza: ["belleza"],
  salud: ["salud"],
  profesional: ["profesional"],
  comercio: ["comercio"],
  industrial: ["industrial"],
  eventos: ["eventos"],
  movilidad: ["movilidad"],
  mas: ["mas"],
};

export const servicesMap: Record<string, string[]> = Object.fromEntries(
  Object.entries(categoryIndustryMap).map(([category, industryIds]) => {
    const bizTypes = businessTypes.filter((biz) =>
      industryIds.includes(businessIndustryMap[biz])
    );
    const serviceNames = [
      ...new Set(
        allServices
          .filter((s) => s.types.some((t) => bizTypes.includes(t)))
          .map((s) => s.name)
      ),
    ];
    return [category, serviceNames];
  })
);
